sudo: false
language: python
python:
  - "3.6"
install:
  - pip install -r requirements/development.txt
  - pip install codeclimate-test-reporter
script:
  - pytest tests
  - codeclimate-test-reporter
